//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int ID_KM { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống ngày bắt đầu")]
        public Nullable<System.DateTime> BatDauKM { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống ngày kết thúc")]
        public Nullable<System.DateTime> KetThucKM { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống nội dung khuyến mãi")]
        [RegularExpression("^[0-9]{1,}$", ErrorMessage = "Nội dung khuyến mãi không hợp lệ (chỉ gồm số)")]
        public string NoiDungKM { get; set; }
        public Nullable<int> LoaiKM { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
