//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.GioHangs = new HashSet<GioHang>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int ID_User { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống tên cá nhân")]
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        [MaxLength(10, ErrorMessage = "Số điện thoại không đúng")]
        [MinLength(10, ErrorMessage = "Số điện thoại không đúng")]
        [Phone(ErrorMessage = "Số điện thoại không đúng")]
        [Required(ErrorMessage ="Không được để trống số điện thoại")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Không được để trống Email")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@gmail.com", ErrorMessage = "E-mail không hợp lệ")]
        public string Email { get; set; }
        public string Anh { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
